export const contactList = [
    {
      id: 1,
      name: "Anubhav Sharma",
      profilePic: "/profile/profilephoto.jpeg",
      lastText: "Hey Man",
      lastTextTime: "12:58 PM",
    },
    {
      id: 2,
      name: "Mayank",
      profilePic: "/profile/pp1.png",
      lastText: `what going on bro`,
      lastTextTime: "12:45 PM",
    },
    {
      id: 3,
      name: "Anjali",
      profilePic: "/profile/pp2.png",
      lastText: "baba lets go out?",
      lastTextTime: "12:30 PM",
    },
    {
      id: 4,
      name: "Kaushal",
      profilePic: "/profile/pp3.jpeg",
      lastText: "no broo",
      lastTextTime: "12:00 PM",
    },
    {
      id: 5,
      name: "Avijit",
      profilePic: "/profile/pp3.jpeg",
      lastText: "no broo",
      lastTextTime: "12:00 PM",
    },
    {
      id: 6,
      name: "Abhay",
      profilePic: "/profile/pp3.jpeg",
      lastText: "no broo",
      lastTextTime: "12:00 PM",
    },
    {
      id: 7,
      name: "Jyoti",
      profilePic: "/profile/pp3.jpeg",
      lastText: "How are you !",
      lastTextTime: "12:00 PM",
    },
    {
      id: 8,
      name: "Irfan",
      profilePic: "/profile/pp3.jpeg",
      lastText: "no broo",
      lastTextTime: "12:00 PM",
    },
    {
      id: 9,
      name: "Newton School",
      profilePic: "/profile/pp3.jpeg",
      lastText: "today class going on ?",
      lastTextTime: "12:00 PM",
    },
    {
      id: 10,
      name: "Old Friends",
      profilePic: "/profile/pp3.jpeg",
      lastText: "It's a party time",
      lastTextTime: "12:00 PM",
    },
    {
      id: 11,
      name: "Sister",
      profilePic: "/profile/pp3.jpeg",
      lastText: "love you sis",
      lastTextTime: "12:00 PM",
    },
    {
      id: 12,
      name: "Love to Code",
      profilePic: "/profile/pp3.jpeg",
      lastText: "Assignement Done",
      lastTextTime: "12:00 PM",
    },
  ];
  export const messagesList = [
    {
      id: 1,
      messageType: "TEXT",
      text: "hello",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "What's up?",
      senderID: 1,
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "All Good, What about you?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "I'm good as well",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Great 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 6,
      messageType: "TEXT",
      text: "Subscribed to Simplilarn",
      senderID: 1,
      addedOn: "12:00 PM",
    },
  ];
